### ISSUE TITLE
How to use in Unity

### ISSUE THREAD

**Issue by tree1891** [imobile-maio/maio-Android-AdMobMediationAdapter#5]

**Comment by im-ade** [comment]
Hi @tree1891  sorry for the late response.

maio is now an admob supported network and are currently phasing out our support for custom events.

If you would like to use maio with admob please use mediation instead.

We currently do not have official documentation on how to use unity with maio at the moment so I will explain the steps and provide you with the links that have the necessary information.

Step 1

You first need to setup your maio and admob dashboards. The steps to set them up can be found at this link (Please follow steps 1 and 2):
https://developers.google.com/admob/android/mediation/maio


Step 2

Next step is to configure your unity project to use admob.
Follow the steps in the link below to download the admob plugin and set it up with your project:
https://developers.google.com/admob/unity/start


Step 3

Once you have completed the previous step add the following two files to your Assets/Plugins/Android directory in your unity project:

Latest Android SDK Jar file from github -> https://github.com/imobile-maio/maio-Android-SDK/releases
Latest maio google adapter aar file from bintray -> https://bintray.com/google/mobile-ads-adapters-android/com.google.ads.mediation.maio#files/com/google/ads/mediation/maio

Step 4

Now your app is all setup. Follow the guides in the link below depending on whether you want to run reward video or interstitial:

https://developers.google.com/admob/unity/interstitial
https://developers.google.com/admob/unity/rewarded-video
